# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 15:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=32, verbose_name='Наименование')),
                ('json', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256, verbose_name='Название события')),
                ('description', models.TextField(blank=True, default='', max_length=16384, verbose_name='Описание события')),
                ('startdate', models.DateTimeField(verbose_name='Начало события')),
                ('enddate', models.DateTimeField(verbose_name='Конец события')),
            ],
            options={
                'verbose_name_plural': 'события',
                'verbose_name': 'событие',
            },
        ),
        migrations.CreateModel(
            name='EventUserRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('r', 'Зарегистрирован'), ('y', 'Посетил'), ('n', 'Не посетил')], default='r', max_length=1, verbose_name='Статус')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(verbose_name='Код')),
                ('html', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='SEO')),
                ('pages', models.ManyToManyField(blank=True, related_name='_page_pages_+', to='core.Page')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=32, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(default='', max_length=32, verbose_name='Фамилия пользователя')),
                ('second_name', models.CharField(blank=True, default='', max_length=32, verbose_name='Отчество пользователя')),
                ('sex', models.CharField(choices=[('U', 'Не выбран'), ('F', 'Женский'), ('M', 'Мужской')], default='U', max_length=1)),
                ('alt_email', models.EmailField(blank=True, max_length=254, verbose_name='Альтернативный e-mail')),
                ('country', django_countries.fields.CountryField(blank=True, default='Russia', max_length=2)),
                ('birthday_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('biography', models.TextField(blank=True, default='', verbose_name='Биография пользователя')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'персоны',
                'verbose_name': 'персона',
            },
        ),
        migrations.CreateModel(
            name='RegistrationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Тип регистрации на мероприятие')),
            ],
        ),
        migrations.AddField(
            model_name='eventuserregistration',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person'),
        ),
        migrations.AddField(
            model_name='eventuserregistration',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.RegistrationType'),
        ),
        migrations.AlterUniqueTogether(
            name='eventuserregistration',
            unique_together=set([('person', 'event')]),
        ),
    ]
