# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 14:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256, verbose_name='Название события')),
                ('description', models.TextField(blank=True, default='', max_length=16384, verbose_name='Описание события')),
                ('startdate', models.DateTimeField(verbose_name='Начало события')),
                ('enddate', models.DateTimeField(verbose_name='Конец события')),
            ],
            options={
                'verbose_name': 'событие',
                'verbose_name_plural': 'события',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=32, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(default='', max_length=32, verbose_name='Фамилия пользователя')),
                ('second_name', models.CharField(blank=True, default='', max_length=32, verbose_name='Отчество пользователя')),
                ('sex', models.CharField(choices=[('U', 'Не выбран'), ('F', 'Женский'), ('M', 'Мужской')], default='U', max_length=1)),
                ('alt_email', models.EmailField(blank=True, max_length=254, verbose_name='Альтернативный e-mail')),
                ('country', django_countries.fields.CountryField(blank=True, default='Russia', max_length=2)),
                ('birthday_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('biography', models.TextField(blank=True, default='', verbose_name='Биография пользователя')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'персона',
                'verbose_name_plural': 'персоны',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(to='core.Speaker'),
        ),
    ]
